include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_const: true
    sort_pub_dependencies: true
    avoid_empty_else: true
    avoid_redundant_argument_values: true
    avoid_returning_null_for_future: true
    no_logic_in_create_state: true
    avoid_unnecessary_containers: true
    use_key_in_widget_constructors: true
    use_super_parameters: true
    avoid_init_to_null: true
    prefer_interpolation_to_compose_strings: true
    unnecessary_new: true
    unnecessary_lambdas: true
    prefer_function_declarations_over_variables: true
